<?php

return [

    'aliases' => [

        'la-coruna'                 => 'A Coruña',
        'coruna'                    => 'A Coruña',
        'araba'                     => 'Álava',
        'alaba'                     => 'Álava',
        'alacant'                   => 'Alicante',
        'bizkaia'                   => 'Vizcaya',
        'biscaia'                   => 'Vizcaya',
        'castello'                  => 'Castellón',
        'gerona'                    => 'Girona',
        'gipuzkoa'                  => 'Guipúzcoa',
        'lerida'                    => 'Lleida',
        'orense'                    => 'Ourense',
        'baleares'                  => 'Illes Balears',
        'islas-baleares'            => 'Illes Balears',
        'balearic-islands'          => 'Illes Balears',

        'bilbao'                    => 'Vizcaya',
        'san-sebastian'             => 'Guipúzcoa',
        'donostia'                  => 'Guipúzcoa',
        'donostia-san-sebastian'    => 'Guipúzcoa',
        'vitoria'                   => 'Álava',
        'vitoria-gasteiz'           => 'Álava',
        'gasteiz'                   => 'Álava',
        'palma'                     => 'Illes Balears',
        'palma-de-mallorca'         => 'Illes Balears',
        'mallorca'                  => 'Illes Balears',
        'ibiza'                     => 'Illes Balears',
        'eivissa'                   => 'Illes Balears',
        'menorca'                   => 'Illes Balears',
        'vigo'                      => 'Pontevedra',
        'santiago-de-compostela'    => 'A Coruña',
        'ferrol'                    => 'A Coruña',
        'oviedo'                    => 'Asturias',
        'gijon'                     => 'Asturias',
        'aviles'                    => 'Asturias',
        'santander'                 => 'Cantabria',
        'pamplona'                  => 'Navarra',
        'iruna'                     => 'Navarra',
        'logrono'                   => 'La Rioja',
        'tenerife'                  => 'Santa Cruz de Tenerife',
        'santa-cruz'                => 'Santa Cruz de Tenerife',
        'la-laguna'                 => 'Santa Cruz de Tenerife',
        'san-cristobal-de-la-laguna' => 'Santa Cruz de Tenerife',
        'gran-canaria'              => 'Las Palmas',
        'las-palmas-de-gran-canaria' => 'Las Palmas',
        'lanzarote'                 => 'Las Palmas',
        'fuerteventura'             => 'Las Palmas',
        'elche'                     => 'Alicante',
        'elx'                       => 'Alicante',
        'benidorm'                  => 'Alicante',
        'cartagena'                 => 'Murcia',
        'jerez-de-la-frontera'      => 'Cádiz',
        'algeciras'                 => 'Cádiz',
        'marbella'                  => 'Málaga',
        'sabadell'                  => 'Barcelona',
        'terrassa'                  => 'Barcelona',
        'badalona'                  => 'Barcelona',
        'hospitalet-de-llobregat'   => 'Barcelona',
        'l-hospitalet-de-llobregat' => 'Barcelona',
        'mataro'                    => 'Barcelona',
        'sant-cugat-del-valles'     => 'Barcelona',
        'reus'                      => 'Tarragona',
        'alcala-de-henares'         => 'Madrid',
        'getafe'                    => 'Madrid',
        'leganes'                   => 'Madrid',
        'mostoles'                  => 'Madrid',
        'alcobendas'                => 'Madrid',
        'las-rozas-de-madrid'       => 'Madrid',
        'pozuelo-de-alarcon'        => 'Madrid',
        'torrelodones'              => 'Madrid',
        'tres-cantos'               => 'Madrid',
        'san-sebastian-de-los-reyes' => 'Madrid',

        'comunidad-de-madrid'       => 'Madrid',
        'comunidad-foral-de-navarra' => 'Navarra',
        'principado-de-asturias'    => 'Asturias',
        'region-de-murcia'          => 'Murcia',
    ],

];
