<?php

return [
    'it_consulting' => [
        'es' => 'Consultoría TI',
        'ca' => 'Consultoria TI',
        'eu' => 'IKT Aholkularitza',
        'gl' => 'Consultoría TI',
        'en' => 'IT Consulting',
    ],
    'software_development' => [
        'es' => 'Desarrollo de Software',
        'ca' => 'Desenvolupament de Software',
        'eu' => 'Software Garapena',
        'gl' => 'Desenvolvemento de Software',
        'en' => 'Software Development',
    ],
    'saas' => [
        'es' => 'SaaS',
        'ca' => 'SaaS',
        'eu' => 'SaaS',
        'gl' => 'SaaS',
        'en' => 'SaaS',
    ],
    'ecommerce' => [
        'es' => 'E-commerce',
        'ca' => 'E-commerce',
        'eu' => 'E-commerce',
        'gl' => 'E-commerce',
        'en' => 'E-commerce',
    ],
    'fintech' => [
        'es' => 'Fintech',
        'ca' => 'Fintech',
        'eu' => 'Fintech',
        'gl' => 'Fintech',
        'en' => 'Fintech',
    ],
    'cybersecurity' => [
        'es' => 'Ciberseguridad',
        'ca' => 'Ciberseguretat',
        'eu' => 'Zibersegurtasuna',
        'gl' => 'Ciberseguridade',
        'en' => 'Cybersecurity',
    ],
    'cloud' => [
        'es' => 'Servicios Cloud',
        'ca' => 'Serveis Cloud',
        'eu' => 'Hodei Zerbitzuak',
        'gl' => 'Servizos Cloud',
        'en' => 'Cloud Services',
    ],
    'ai_data' => [
        'es' => 'IA y Datos',
        'ca' => 'IA i Dades',
        'eu' => 'AA eta Datuak',
        'gl' => 'IA e Datos',
        'en' => 'AI & Data',
    ],
    'healthtech' => [
        'es' => 'Healthtech',
        'ca' => 'Healthtech',
        'eu' => 'Healthtech',
        'gl' => 'Healthtech',
        'en' => 'Healthtech',
    ],
    'edtech' => [
        'es' => 'EdTech',
        'ca' => 'EdTech',
        'eu' => 'EdTech',
        'gl' => 'EdTech',
        'en' => 'EdTech',
    ],
    'gaming' => [
        'es' => 'Videojuegos',
        'ca' => 'Videojocs',
        'eu' => 'Bideojokoak',
        'gl' => 'Videoxogos',
        'en' => 'Gaming',
    ],
    'telecommunications' => [
        'es' => 'Telecomunicaciones',
        'ca' => 'Telecomunicacions',
        'eu' => 'Telekomunikazioak',
        'gl' => 'Telecomunicacións',
        'en' => 'Telecommunications',
    ],
    'recruitment' => [
        'es' => 'Selección de Personal',
        'ca' => 'Selecció de Personal',
        'eu' => 'Langileak Hautatzea',
        'gl' => 'Selección de Persoal',
        'en' => 'Recruitment',
    ],
    'logistics_tech' => [
        'es' => 'Tecnología Logística',
        'ca' => 'Tecnologia Logística',
        'eu' => 'Logistika Teknologia',
        'gl' => 'Tecnoloxía Loxística',
        'en' => 'Logistics Tech',
    ],
    'media_adtech' => [
        'es' => 'Media y AdTech',
        'ca' => 'Media i AdTech',
        'eu' => 'Media eta AdTech',
        'gl' => 'Media e AdTech',
        'en' => 'Media & AdTech',
    ],
    'iot' => [
        'es' => 'Internet de las Cosas',
        'ca' => 'Internet de les Coses',
        'eu' => 'Gauzen Internet',
        'gl' => 'Internet das Cousas',
        'en' => 'IoT',
    ],
    'other' => [
        'es' => 'Otro',
        'ca' => 'Altre',
        'eu' => 'Beste bat',
        'gl' => 'Outro',
        'en' => 'Other',
    ],
];
